name: Bot VPS Simulasi

on:
  workflow_dispatch:

jobs:
  vps-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python & Tools
        run: |
          sudo apt update
          sudo apt install -y python3 nmap

      - name: Simulasi Bot VPS
        run: |
          python3 -c "print('Bot online dan siap kirim data...')"
          curl ifconfig.me  # lihat IP publik GitHub bot
